# Generated by Django 3.1.6 on 2021-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treeko', '0002_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='newreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('area', models.IntegerField(default=2)),
                ('aadhar', models.ImageField(upload_to='pics')),
                ('land_docs', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
