# Generated by Django 3.1.6 on 2021-02-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Treeko', '0003_newreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proof',
            old_name='username',
            new_name='urname',
        ),
    ]
