# Generated by Django 3.1.6 on 2021-02-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treeko', '0004_auto_20210214_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newreq',
            name='aadhar',
            field=models.ImageField(upload_to='pics2'),
        ),
        migrations.AlterField(
            model_name='newreq',
            name='land_docs',
            field=models.ImageField(upload_to='pics2'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='image1',
            field=models.ImageField(upload_to='pics3'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='image2',
            field=models.ImageField(upload_to='pics3'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='image3',
            field=models.ImageField(upload_to='pics3'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='image4',
            field=models.ImageField(upload_to='pics3'),
        ),
    ]
